### ISSUE TITLE
[Bug]: [macOS M2] Rendering & Compatibility Issues in Drone Example

### ISSUE THREAD

**Issue by Revivekirin** [Genesis-Embodied-AI/Genesis#1125]
### Bug Description

Hello, I’m currently running the Genesis library’s drone example on macOS with an M2 chip. While working with the hover_train.py and hover_eval.py scripts, I encountered several rendering issues in the macOS environment:

1. In `hover_env.py`, the code fails to run unless the `rpy` and `degrees` arguments are removed. The error message states: unexpected keyword argument. Could you clarify why these arguments are not supported?

<img width="1256" alt="Image" src="https://github.com/user-attachments/assets/eee1ce89-f3d8-42e6-8002-750ef9c95a2d" />

2. The` rendering_on_macos.py` file, which was previously used for macOS rendering, seems to have been removed. While `run_in_another_thread` works with `genesis-world `version 0.2.1, it would be helpful if you could re-upload the file so I can inspect the function definitions in more detail.

3. When` cam.GUI=True`, there is a conflict between `cv2.imshow()` and the Metal backend on macOS. Setting `cam.GUI=False `avoids the issue and allows the code to run.

4. There seems to be a version conflict between the `genesis-world==0.2.1 `package and the versions specified in `pyproject.toml` The example scripts only run properly if the `genesis-world` library is explicitly pinned to version 0.2.1. Is this behavior related to the upcoming v3 update?

Thank you in advance for your response, and thank you for your great work on this open-source project!

### Argument are not supported on macos
```
self.base_euler = quat_to_xyz(
            transform_quat_by_quat(torch.ones_like(self.base_quat) * self.inv_base_init_quat, self.base_quat),
            # rpy=True,
            # degrees=True,
        )
```
### Still have to use `run_in_another_thread`for running on macos
```
    gs.tools.run_in_another_thread(
        fn=simulate,
        args=(),
    )

```

### Expected Behavior

The` hover_train.py `and `hover_eval.py` scripts should run without errors on macOS (Apple Silicon), including:

1. No unexpected keyword argument errors in `hover_env.py`
2. Compatibility with the default library versions specified in `pyproject.toml`
3. Access to macOS-specific rendering utilities such as `rendering_on_macos.py `for debugging or extension

### Environment

- OS: MacOS 15.4.1
- GPU/CPU metal/m2

### Release version or Commit ID

genesis-world==0.2.1
Commit ID: `a0eedddf63aa13cfb0bb64f7b9446c9ca2d511d6`

**Comment by duburcqa** [comment]
You should install the latest version (which is not available on PyPI yet) to get full Windows OS support. The instructions are provided in README. Ping me on this issue if it still does not work after that and I will reopen it.
